import localFont from "next/font/local";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import NavBar from "./components/Nav/NavBar";
import SideBar from "./components/Nav/SideBar";
import { SidebarProvider } from './context/SidebarProvider';
import { FetchProductProvider } from './context/FetchProductProvider'; // Ensure this path is correct

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "GoTrip",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SidebarProvider>
          <NavBar />
          <SideBar />
          <FetchProductProvider>
            {children}
          </FetchProductProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
